---
title: "Untitled"
output: html_document
date: "2024-12-10"
editor_options: 
  chunk_output_type: console
---

# Importation des données
```{r}
setwd("/Users/kentookado/M1SSD/Projet tutore - CINEDESIM")

library(readxl)
df = read_excel("~/M1SSD/Projet tutore - CINEDESIM/Datasets/Données Finales projet CINE-DESIM.xlsx" , col_names=T)

## Nettoyage des donnees:
#on renomme distinctivement les variables
df[1,8] = "MFI  CLASSE I"
df[1,10] = "Prozone CLASSE I"
df[1,16] = "MFI CLASSE II"
df[1,18] = "Prozone CLASSE II"

# suprime les colonnes t1 doublees (le patient 6 a t1 et t2 doubles)
df = df[-c(2,24,46,68,90,112,113,135,157,179,201),]

# supprime les colonnes avec que des NA
df = df[!is.na(df$...1),]

# fonction qui met la premiere ligne comme nom de variable
header.true <- function(df) {
  names(df) <- as.character(unlist(df[1,]))
  df[-1,]
}
df = header.true(df)

# prend les variables qui nous interesse (est-ce que se sont les bonnes?)
df = subset(df, select= c(1,2,5,8,9,10,16,17,18,20,21,22,24,25,26,27,28,29,30,31,32,33,36))

# on remplace les ”oui" par "Oui" dans la variable Transfusion
df$Transfusion = replace(df$Transfusion, df$Transfusion=="oui", "Oui")

## Definition et structuration des donnees:
df$`Nom du Batch` = factor(df$`Nom du Batch`)
df$Time = factor(df$Time)
df$`Type de locus` = factor(df$`Type de locus`)
df$`MFI  CLASSE I` = as.double(df$`MFI  CLASSE I`)
df$`PRA CLASSE I` = as.double(df$`PRA CLASSE I`)
df$`Prozone CLASSE I` = factor((df$`Prozone CLASSE I`))
df$`MFI CLASSE II` = as.double(df$`MFI CLASSE II`)
df$`PRA CLASSE II` = as.double(df$`PRA CLASSE II`)
df$`Prozone CLASSE II` = factor((df$`Prozone CLASSE II`))
df$`Date séance` = as.double(df$`Date séance`)
df$`Heure début (branchement)` = as.double(df$`Heure début (branchement)`)
df$`Heure fin (débranchement)` = as.double(df$`Heure fin (débranchement)`)
df$`Nombre d'utilisation de la colonne` = as.double(df$`Nombre d'utilisation de la colonne`)
df$`Monet : O/N` = factor(df$`Monet : O/N`)
df$`Volume plasma prescrit` = as.double(df$`Volume plasma prescrit`)
df$`Volume plasma traite` = as.double(df$`Volume plasma traite`)
df$DDN = as.double(df$DDN)
df$`Poids (kg)` = as.double(df$`Poids (kg)`)
df$`Taille (cm)` = as.double(df$`Taille (cm)`)
df$Sexe = factor(df$Sexe)
df$Grossesses = as.double(df$Grossesses)
df$`Greffe anterieur` = as.double(df$`Greffe anterieur`)
df$Transfusion = factor(df$Transfusion)
df$deltaMFI
```

# Nettoyage des données
## Séparation des données par individus
```{r}
df1 = subset(df, df$`Nom du Batch`=="Patient 1")
df2 = subset(df, df$`Nom du Batch`=="Patient 2")
df3 = subset(df, df$`Nom du Batch`=="Patient 3")
df4 = subset(df, df$`Nom du Batch`=="Patient 4")
df5 = subset(df, df$`Nom du Batch`=="Patient 5")
df6 = subset(df, df$`Nom du Batch`=="Patient 6")
df7 = subset(df, df$`Nom du Batch`=="Patient 7")
df8 = subset(df, df$`Nom du Batch`=="Patient 8")
df9 = subset(df, df$`Nom du Batch`=="Patient 9")
df10 = subset(df, df$`Nom du Batch`=="Patient 10")
df7_1 = subset(df, df$`Nom du Batch`=="Patient 7 1/5")
df2_1 = subset(df, df$`Nom du Batch`=="Patient 2  1/10")

df_list = list(df1,df2,df3,df4,df5,df6,df7,df8, df9, df10, df7_1, df2_1)
```

## Valeurs manquantes
```{r}
na.heure_debut = function(df) {
  df$`Heure début (branchement)`[is.na(df$`Heure début (branchement)`)] = mean(df$`Heure début (branchement)`, na.rm=T)
  return(df)
}

df_list = lapply(df_list, na.heure_debut)
```

```{r}
na.heure_fin = function(df) {
 df$`Heure fin (débranchement)` = ifelse(is.na(df$`Heure fin (débranchement)`), df$`Heure début (branchement)` + mean(df$`Heure fin (débranchement)`-df$`Heure début (branchement)`, na.rm=T), df$`Heure fin (débranchement)`)
 return(df)
}

df_list = lapply(df_list, na.heure_fin)
```

```{r}
na.date = function(df) {
  for (i in 2:length(df$`Date séance`)) {
    if (is.na(df$`Date séance`[i])) {
      df$`Date séance`[i] = df$`Date séance`[i-1]
    }
  }
  return(df)
}

df_list = lapply(df_list, na.date)

df_list[[6]]$`Date séance`[is.na(df_list[[6]]$`Date séance`)] = 43745  # manuellement car t1 et t2 manquants
```

```{r}
na.type_locus = function(df) {
  for (i in 2:length((df$`Type de locus`))) {
    if (is.na(df$`Type de locus`[i])){
      if (is.na(df$`Type de locus`[i-1])==F) {df$`Type de locus`[i]=df$`Type de locus`[i-1]}
      else {df$`Type de locus`[i]=df$`Type de locus`[i+1]}
    }
  }
  return(df)
}

df_list = lapply(df_list, na.type_locus)
```

```{r}
na.vol_plasma_traite = function(df) {
  for (i in 2:length(df$`Volume plasma traite`)){
    if (is.na(df$`Volume plasma traite`[i])) {
      df$`Volume plasma traite`[i] = mean(df$`Volume plasma traite`, na.rm=T)
    }
  }
  return(df)
}

df_list = lapply(df_list, na.type_locus)
```


# Ajout de nouvelle variable
```{r}
df_duree = function(df) {
  df$duree = (df$`Heure fin (débranchement)` - df$`Heure début (branchement)`)*24
  return(df)
}

df_list = lapply(df_list, df_duree)
```

```{r}
df_temps = function(df){
  temps = c(0)
  for (i in seq(2,nrow(df)+1,2)) {
    duree_seance = temps[i-1]+ (df$`Heure fin (débranchement)`[i]-df$`Heure début (branchement)`[i])*24
    duree_entre_seance = duree_seance + (df$`Date séance`[i+1]-df$`Date séance`[i])*24 + df$`Heure début (branchement)`[i+1]*24
    temps = c(temps, duree_seance, duree_entre_seance)
  }
  df$temps = temps[1:20]
  return(df)
}

df_list = lapply(df_list, df_temps)
```


# Creation du nouveau dataframe
```{r}
df = rbind(df_list[[1]],df_list[[2]],df_list[[3]],df_list[[4]],df_list[[5]],df_list[[6]],df_list[[7]],df_list[[8]],
           df_list[[9]],df_list[[10]],df_list[[11]],df_list[[12]])
```



# Spagetti plot
```{r}
my.max <- function(x) ifelse( !all(is.na(x)), max(x, na.rm=T), NA)
my.min <- function(x) ifelse( !all(is.na(x)), min(x, na.rm=T), NA)

plot.MFI = function(x,df_list) {
  if (x==1) {
    plot(df_list[[1]]$temps[1:20], df_list[[1]]$`MFI  CLASSE I`, type="l", col=1, ylim=c(0,my.max(df$`MFI  CLASSE I`)), xlim=c(0,450), ylab="MFI classe 1", xlab="temps")
    for (i in 3:length(df_list)) {
      lines(df_list[[i]]$temps[1:20], df_list[[i]]$`MFI  CLASSE I`, type="l", col=i)
    }
    abline(h=3000,lty=2)
    legend("topright",c("patient 1", "patient 3", "patient 4", "patient 5", "patient 6", "patient 7",
                        "patient 8", "patient 9", "patient 10", "patient 2 1/10"), 
           col=c(1,3,4,5,6,7,8,9,10,11), lty = 1, cex=0.65)
  }
  else {
    plot(df_list[[1]]$temps[1:20], df_list[[1]]$`MFI CLASSE II`, type="l", col=1, ylim=c(0,30000), xlim=c(0,450), ylab="MFI classe 2", xlab="temps")
    for (i in 2:length(df_list)) {
      lines(df_list[[i]]$temps[1:20], df_list[[i]]$`MFI CLASSE II`, type="l", col=i)
    }
    abline(h=3000,lty=2)
    legend("topright",c("patient 1", "patient 2", "patient 3", "patient 5", "patient 6", "patient 7",
                       "patient 9", "patient 10", "patient 7 1/5"), 
           col=c(1,2,3,5,6,7,9,10,11), lty = 1, cex=0.65)
  }
}

plot.MFI(1,df_list)
plot.MFI(2,df_list)
```

```{r}
df_MFIclassI = rbind(df_list[[1]],df_list[[3]],df_list[[4]],df_list[[5]],df_list[[6]],df_list[[7]],
                     df_list[[8]], df_list[[9]],df_list[[10]],df_list[[12]])
ggplot(df_MFIclassI, aes(x = temps, y = `MFI  CLASSE I`, 
                         group=as.factor(`Nom du Batch`), color=as.factor(`Nom du Batch`))) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 3000, color = "black", linetype = "dashed") +
  labs(x = "Time in hours",
       y = "MFI class I",
       color="Patient")
  # + scale_x_continuous(breaks = seq(0, 450, by = 24))
```

```{r}
df_MFIclassII = rbind(df_list[[1]],df_list[[2]], df_list[[3]],df_list[[5]],df_list[[6]],df_list[[7]], df_list[[9]],df_list[[10]],df_list[[11]])
ggplot(df_MFIclassII, aes(x = temps, y = `MFI CLASSE II`, 
                         group=as.factor(`Nom du Batch`), color=as.factor(`Nom du Batch`))) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 3000, color = "black", linetype = "dashed") +
  labs(x = "Time in hours",
       y = "MFI class II",
       color="Patient")
  # + scale_x_continuous(breaks = seq(0, 450, by = 24))
```

# Delta du MFI
```{r}
delta_MFI = function(df) {
  delta1 = numeric(20)
  delta2 = numeric(20)
  for (i in 1:10){
    delta1[2*i-1] = df$`MFI  CLASSE I`[2*i] - df$`MFI  CLASSE I`[2*i-1]
    delta1[2*i] = df$`MFI  CLASSE I`[2*i] - df$`MFI  CLASSE I`[2*i-1]
    delta2[2*i-1] = df$`MFI CLASSE II`[2*i] - df$`MFI CLASSE II`[2*i-1]
    delta2[2*i] = df$`MFI CLASSE II`[2*i] - df$`MFI CLASSE II`[2*i-1]
  }
  df$deltaMFI1 = delta1
  df$deltaMFI2 = delta2
  df$seance = c(1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10)
  return(df[-seq(1,20,2),])
}

df_list_delta = lapply(df_list, delta_MFI)
```

```{r}
plot.deltaMFI = function(x) {
  if(x==1){
    plot(1:10, -df_list_delta[[1]]$deltaMFI1, col=1, type="l", ylim=c(-10000,10000), xlim=c(1,10), ylab="delta du MFI classe I", xlab="séance")
    grid(nx = NULL,
     ny = NA,
     lty = 2, col = "gray", lwd = 2)
    for (i in 3:length(df_list)) {
      lines(1:10, -df_list_delta[[i]]$deltaMFI1, col=i)
    }
    abline(h=0)
    legend("bottomright",c("patient 1", "patient 3", "patient 4", "patient 5", "patient 6", "patient 7",
                        "patient 8", "patient 9", "patient 10", "patient 2 1/10"), 
           col=c(1,3,4,5,6,7,8,9,10,11), lty = 1, cex=0.65)
  }
  else{
    plot(1:10, -df_list_delta[[1]]$deltaMFI2, col=1, type="l", ylim=c(-7000,12000), ylab="delta du MFI classe II", xlab="séance")
    for (i in 2:length(df_list)) {
      lines(1:10, -df_list_delta[[i]]$deltaMFI2, col=i)
      }
    abline(h=0)
    legend("bottomright",c("patient 1", "patient 2", "patient 3", "patient 5", "patient 6", "patient 7",
                       "patient 9", "patient 10", "patient 7 1/5"), 
           col=c(1,2,3,5,6,7,9,10,11), lty = 1, cex=0.65)
    }
  }
plot.deltaMFI(1)
plot.deltaMFI(2)
```

```{r}
df_deltaMFIclassI = rbind(df_list_delta[[1]],df_list_delta[[3]],df_list_delta[[4]],df_list_delta[[5]],df_list_delta[[6]],
                          df_list_delta[[7]], df_list_delta[[8]], df_list_delta[[9]],df_list_delta[[10]],
                          df_list_delta[[12]])

ggplot(df_deltaMFIclassI, aes(x=seance, y = - deltaMFI1, 
                         group=as.factor(`Nom du Batch`), color=as.factor(`Nom du Batch`))) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 0, color = "black", linetype = "dashed") +
  labs(x = "Session",
       y = "Delta of MFI class I",
       color="Patient") + 
  scale_x_continuous(breaks = seq(0, 10, by = 1))
```

```{r}
df_deltaMFIclassI = rbind(df_list_delta[[1]],df_list_delta[[2]],df_list_delta[[3]],df_list_delta[[5]],df_list_delta[[6]],
                          df_list_delta[[7]], df_list_delta[[9]],df_list_delta[[10]],
                          df_list_delta[[11]])

ggplot(df_deltaMFIclassI, aes(x=seance, y = - deltaMFI2, 
                         group=as.factor(`Nom du Batch`), color=as.factor(`Nom du Batch`))) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 0, color = "black", linetype = "dashed") +
  labs(x = "Session",
       y = "Delta of MFI class II",
       color="Patient") + 
  scale_x_continuous(breaks = seq(0, 10, by = 1))
```

# Modèle non linéaire à effets mixtes
```{r}
library(nlme)
```