---
title: "CINEDESIM"
output: html_document
date: "2024-11-13"
editor_options: 
  chunk_output_type: console
---

```{r}
setwd("/Users/kentookado/M1SSD/Projet tutore - CINEDESIM")

library(readxl)
df = read_excel("~/M1SSD/Projet tutore - CINEDESIM/Datasets/Données Finales projet CINE-DESIM.xlsx" , col_names=T)

## Nettoyage des donnees:
#on renomme distinctivement les variables
df[1,8] = "MFI  CLASSE I"
df[1,10] = "Prozone CLASSE I"
df[1,16] = "MFI CLASSE II"
df[1,18] = "Prozone CLASSE II"

# suprime les colonnes t1 doublees (le patient 6 a t1 et t2 doubles)
df = df[-c(2,24,46,68,90,112,113,135,157,179,201),]

# supprime les colonnes avec que des NA
df = df[!is.na(df$...1),]

# fonction qui met la premiere ligne comme nom de variable
header.true <- function(df) {
  names(df) <- as.character(unlist(df[1,]))
  df[-1,]
}

# prend les variables qui nous interesse (est-ce que se sont les bonnes?)
df = header.true(subset(df, select= c(1,2,5,8,9,10,16,17,18,20,21,22,24,25,26,27,28,29,30,31,32,33,36)))

# on remplace les ”oui" par "Oui" dans la variable Transfusion
df$Transfusion = replace(df$Transfusion, df$Transfusion=="oui", "Oui")

## Definition et structuration des donnees:
df$`Nom du Batch` = factor(df$`Nom du Batch`)
df$Time = factor(df$Time)
df$`Type de locus` = factor(df$`Type de locus`)
df$`MFI  CLASSE I` = as.double(df$`MFI  CLASSE I`)
df$`PRA CLASSE I` = as.double(df$`PRA CLASSE I`)
df$`Prozone CLASSE I` = factor((df$`Prozone CLASSE I`))
df$`MFI CLASSE II` = as.double(df$`MFI CLASSE II`)
df$`PRA CLASSE II` = as.double(df$`PRA CLASSE II`)
df$`Prozone CLASSE II` = factor((df$`Prozone CLASSE II`))
df$`Date séance` = as.double(df$`Date séance`)
df$`Heure début (branchement)` = as.double(df$`Heure début (branchement)`)
df$`Heure fin (débranchement)` = as.double(df$`Heure fin (débranchement)`)
df$`Nombre d'utilisation de la colonne` = as.double(df$`Nombre d'utilisation de la colonne`)
df$`Monet : O/N` = factor(df$`Monet : O/N`)
df$`Volume plasma prescrit` = as.double(df$`Volume plasma prescrit`)
df$`Volume plasma traite` = as.double(df$`Volume plasma traite`)
df$DDN = as.double(df$DDN)
df$`Poids (kg)` = as.double(df$`Poids (kg)`)
df$`Taille (cm)` = as.double(df$`Taille (cm)`)
df$Sexe = factor(df$Sexe)
df$Grossesses = as.double(df$Grossesses)
df$`Greffe anterieur` = as.double(df$`Greffe anterieur`)
df$Transfusion = factor(df$Transfusion)



# construction de la variable duree de la duree de la seance
df$duree = (df$`Heure fin (débranchement)` - df$`Heure début (branchement)`)*24*60
           

# construction de la variable duree totale de la duree totale cummule des sceances
df$duree_totale
```

```{r}
## Etude des differences de MFI entre t1 et t20 pour chaque patient
MFI_I_diff = df$`MFI  CLASSE I`[which(df$Time=="t20")]- df$`MFI  CLASSE I`[which(df$Time=="t1")]
df_MFI_I_diff = data.frame(x=levels(df$`Nom du Batch`), y=MFI_I_diff) # faux dataframe, l'ordre de levels(df$...) est pas bon par rapport a l'ordre  des noms dans df

MFI_II_diff = df$`MFI CLASSE II`[which(df$Time=="t20")]- df$`MFI CLASSE II`[which(df$Time=="t1")]
df_MFI_I_diff = data.frame(x=levels(df$`Nom du Batch`), y=MFI_II_diff)  # faux dataframe

MFI_diff = cbind(MFI_I_diff,MFI_II_diff)
boxplot(MFI_diff, beside=T)

#creation de la variable MFI_diff pour chaque patient
df$MFI1_diff = ifelse(df$`Nom du Batch`=="Patient 1", MFI_I_diff[1],
                      ifelse(df$`Nom du Batch`=="Patient 2", MFI_I_diff[2],
                      ifelse(df$`Nom du Batch`=="Patient 3", MFI_I_diff[3], 
                      ifelse(df$`Nom du Batch`=="Patient 4", MFI_I_diff[4],
                      ifelse(df$`Nom du Batch`=="Patient 5", MFI_I_diff[5],
                      ifelse(df$`Nom du Batch`=="Patient 6", MFI_I_diff[6],
                      ifelse(df$`Nom du Batch`=="Patient 7", MFI_I_diff[7],
                      ifelse(df$`Nom du Batch`=="Patient 8", MFI_I_diff[8],
                      ifelse(df$`Nom du Batch`=="Patient 9", MFI_I_diff[9],
                      ifelse(df$`Nom du Batch`=="Patient 10", MFI_I_diff[10],
                      ifelse(df$`Nom du Batch`=="Patient 7 1/5", MFI_I_diff[11],
                      MFI_I_diff[12]
                      )))))))))))

df$MFI2_diff = ifelse(df$`Nom du Batch`=="Patient 1", MFI_II_diff[1],
                      ifelse(df$`Nom du Batch`=="Patient 2", MFI_II_diff[2],
                             ifelse(df$`Nom du Batch`=="Patient 3", MFI_II_diff[3], 
                                    ifelse(df$`Nom du Batch`=="Patient 4", MFI_II_diff[4],
                                           ifelse(df$`Nom du Batch`=="Patient 5", MFI_II_diff[5],
                                                  ifelse(df$`Nom du Batch`=="Patient 6", MFI_II_diff[6],
                                                         ifelse(df$`Nom du Batch`=="Patient 7", MFI_II_diff[7],
                                                                ifelse(df$`Nom du Batch`=="Patient 8", MFI_II_diff[8],
                                                                       ifelse(df$`Nom du Batch`=="Patient 9", MFI_II_diff[9],
                                                                              ifelse(df$`Nom du Batch`=="Patient 10", MFI_II_diff[10],
                                                                                     ifelse(df$`Nom du Batch`=="Patient 7 1/5", MFI_II_diff[11],
                                                                                            MFI_II_diff[12]
                                                                                     )))))))))))

#boxplot de la difference de MFI1 entre t20 et t1 en fonction des variables sexe, grossesses, greffe anterieur et transfusion
boxplot(df$MFI1_diff[which(df$Time=="t1")]~df$Sexe[which(df$Time=="t1")])
boxplot(df$MFI1_diff[which(df$Time=="t1")]~df$Grossesses[which(df$Time=="t1")])
boxplot(df$MFI1_diff[which(df$Time=="t1")]~df$`Greffe anterieur`[which(df$Time=="t1")])
boxplot(df$MFI1_diff[which(df$Time=="t1")]~df$Transfusion[which(df$Time=="t1")])
```

```{r}
## Comparaison de l'evolution de MFI CLASSE I en fonction de Time de tous les patients
my.max <- function(x) ifelse( !all(is.na(x)), max(x, na.rm=T), NA)
my.min <- function(x) ifelse( !all(is.na(x)), min(x, na.rm=T), NA)

# MFI Classe I
plot((1:20), df$`MFI  CLASSE I`[which(df$`Nom du Batch`=="Patient 1")], type="l", col=1, ylim=c(my.min(df$`MFI  CLASSE I`),my.max(df$`MFI  CLASSE I`)))
plot((1:20), df$`MFI  CLASSE I`[which(df$`Nom du Batch`=="Patient 2")], type="l", col=2)
lines((1:20), df$`MFI  CLASSE I`[which(df$`Nom du Batch`=="Patient 3")], type="l", col=3)
lines((1:20), df$`MFI  CLASSE I`[which(df$`Nom du Batch`=="Patient 4")], type="l", col=4)
lines((1:20), df$`MFI  CLASSE I`[which(df$`Nom du Batch`=="Patient 5")], type="l", col=5)
plot((1:20), df$`MFI  CLASSE I`[which(df$`Nom du Batch`=="Patient 6")], type="l", col=6)
lines((1:20), df$`MFI  CLASSE I`[which(df$`Nom du Batch`=="Patient 7")], type="l", col=7)
lines((1:20), df$`MFI  CLASSE I`[which(df$`Nom du Batch`=="Patient 8")], type="l", col=8)
lines((1:20), df$`MFI  CLASSE I`[which(df$`Nom du Batch`=="Patient 9")], type="l", col=9)
lines((1:20), df$`MFI  CLASSE I`[which(df$`Nom du Batch`=="Patient 10")], type="l", col=10)
lines((1:20), df$`MFI  CLASSE I`[which(df$`Nom du Batch`=="Patient 2 1/10")], type="l", col=11)
lines((1:20), df$`MFI  CLASSE I`[which(df$`Nom du Batch`=="Patient 7 1/5")], type="l", col=12)
```

```{r}
# MFI Classe II
plot((1:20), df$`MFI CLASSE II`[which(df$`Nom du Batch`=="Patient 1")], type="l", col=1, ylim=c(my.min(df$`MFI CLASSE II`),my.max(df$`MFI CLASSE II`)))
lines((1:20), df$`MFI CLASSE II`[which(df$`Nom du Batch`=="Patient 2")], type="l", col=2)
lines((1:20), df$`MFI CLASSE II`[which(df$`Nom du Batch`=="Patient 3")], type="l", col=3)
lines((1:20), df$`MFI CLASSE II`[which(df$`Nom du Batch`=="Patient 4")], type="l", col=4)
lines((1:20), df$`MFI CLASSE II`[which(df$`Nom du Batch`=="Patient 5")], type="l", col=5)
lines((1:20), df$`MFI CLASSE II`[which(df$`Nom du Batch`=="Patient 6")], type="l", col=6)
lines((1:20), df$`MFI CLASSE II`[which(df$`Nom du Batch`=="Patient 7")], type="l", col=7)
lines((1:20), df$`MFI CLASSE II`[which(df$`Nom du Batch`=="Patient 8")], type="l", col=8)
lines((1:20), df$`MFI CLASSE II`[which(df$`Nom du Batch`=="Patient 9")], type="l", col=9)
lines((1:20), df$`MFI CLASSE II`[which(df$`Nom du Batch`=="Patient 10")], type="l", col=10)
# lines((1:20), df$`MFI CLASSE II`[which(df$`Nom du Batch`=="Patient 2 1/10")], type="l", col=11)  -> patient 2 1/5 n'a pas de MFI2
lines((1:20), df$`MFI CLASSE II`[which(df$`Nom du Batch`=="Patient 7 1/5")], type="l", col=12)
```


```{r}
## Etude du patient 3
# plot du MFI CLASSE I et MFI CLASSE II en fonction des t (et pas des durees)
df3 = subset(df, df$`Nom du Batch`=="Patient 3")
plot((1:20), df3$`MFI  CLASSE I`, type="l", col="red")
lines((1:20), df3$`MFI CLASSE II`, type="l", col="blue")

# ajout de la varialbe deltaMFI de la diffenrece de MFI entre le debut en fin de seance
toto = matrix(NA, ncol=1, nrow=20)
for (i in 1:10){
  toto[2*i-1] = df3$`MFI  CLASSE I`[which(df3$Time==paste0("t",2*i))]- df3$`MFI  CLASSE I`[which(df3$Time==paste0("t",2*i-1))]
  toto[2*i] = df3$`MFI  CLASSE I`[which(df3$Time==paste0("t",2*i))]- df3$`MFI  CLASSE I`[which(df3$Time==paste0("t",2*i-1))]
  
}
df3$deltaMFI = toto
```

```{r}
df1 = subset(df, df$`Nom du Batch`=="Patient 1")

temps = c(0)

for (i in seq(2,nrow(df1)+1,2)) {
  duree_seance = temps[i-1]+ (df1$`Heure fin (débranchement)`[i]-df1$`Heure début (branchement)`[i])*24*60
  duree_entre_seance = duree_seance + (df1$`Date séance`[i+1]-df1$`Date séance`[i])*24*60 + df1$`Heure début (branchement)`[i+1]*24*60
  temps = c(temps, duree_seance, duree_entre_seance)
}

layout(matrix(1,1),1)
plot(temps[1:20], df1$`MFI  CLASSE I`, type="l")
```

```{r}
df2 = subset(df, df$`Nom du Batch`=="Patient 2")

df2$`Heure fin (débranchement)` = ifelse(is.na(df2$`Heure fin (débranchement)`), df2$`Heure début (branchement)` + mean(df2$`Heure fin (débranchement)`-df2$`Heure début (branchement)`, na.rm=T), df2$`Heure fin (débranchement)`)

df2$`Date séance`[is.na(df2$`Date séance`)] = 43566


temps = c(0)

for (i in seq(2,nrow(df2)+1,2)) {
  duree_seance = temps[i-1]+ (df2$`Heure fin (débranchement)`[i]-df2$`Heure début (branchement)`[i])*24*60
  duree_entre_seance = duree_seance + (df2$`Date séance`[i+1]-df2$`Date séance`[i])*24*60 + df2$`Heure début (branchement)`[i+1]*24*60
  temps = c(temps, duree_seance, duree_entre_seance)
}

layout(matrix(1,1),1)
plot(temps[1:20], df2$`MFI  CLASSE I`, type="l")

```

```{r}
df3 = subset(df, df$`Nom du Batch`=="Patient 3")

df3$`Heure fin (débranchement)` = ifelse(is.na(df3$`Heure fin (débranchement)`), df3$`Heure début (branchement)` + mean(df3$`Heure fin (débranchement)`-df3$`Heure début (branchement)`, na.rm=T), df3$`Heure fin (débranchement)`)

temps = c(0)

for (i in seq(2,nrow(df3)+1,2)) {
  duree_seance = temps[i-1]+ (df3$`Heure fin (débranchement)`[i]-df3$`Heure début (branchement)`[i])*24*60
  duree_entre_seance = duree_seance + (df3$`Date séance`[i+1]-df3$`Date séance`[i])*24*60 + df3$`Heure début (branchement)`[i+1]*24*60
  temps = c(temps, duree_seance, duree_entre_seance)
}

layout(matrix(1,1),1)
plot(temps[1:20], df3$`MFI  CLASSE I`, type="l")
```

```{r}
df4 = subset(df, df$`Nom du Batch`=="Patient 5")

df4$`Heure fin (débranchement)` = ifelse(is.na(df4$`Heure fin (débranchement)`), df4$`Heure début (branchement)` + mean(df4$`Heure fin (débranchement)`-df4$`Heure début (branchement)`, na.rm=T), df4$`Heure fin (débranchement)`)

temps = c(0)
for (i in seq(2,nrow(df4)+1,2)) {
  duree_seance = temps[i-1]+ (df4$`Heure fin (débranchement)`[i]-df4$`Heure début (branchement)`[i])*24*60
  duree_entre_seance = duree_seance + (df4$`Date séance`[i+1]-df4$`Date séance`[i])*24*60 + df4$`Heure début (branchement)`[i+1]*24*60
  temps = c(temps, duree_seance, duree_entre_seance)
}
layout(matrix(1,1),1)
plot(temps[1:20], df4$`MFI  CLASSE I`, type="l")
```

```{r}
df5 = subset(df, df$`Nom du Batch`=="Patient 5")

df5$`Heure fin (débranchement)` = ifelse(is.na(df5$`Heure fin (débranchement)`), df5$`Heure début (branchement)` + mean(df5$`Heure fin (débranchement)`-df5$`Heure début (branchement)`, na.rm=T), df5$`Heure fin (débranchement)`)

temps = c(0)
for (i in seq(2,nrow(df5)+1,2)) {
  duree_seance = temps[i-1]+ (df5$`Heure fin (débranchement)`[i]-df5$`Heure début (branchement)`[i])*24*60
  duree_entre_seance = duree_seance + (df5$`Date séance`[i+1]-df5$`Date séance`[i])*24*60 + df5$`Heure début (branchement)`[i+1]*24*60
  temps = c(temps, duree_seance, duree_entre_seance)
}
layout(matrix(1,1),1)
plot(temps[1:20], df5$`MFI  CLASSE I`, type="l")
```

```{r}
df6 = subset(df, df$`Nom du Batch`=="Patient 6")

df6$`Heure fin (débranchement)` = ifelse(is.na(df6$`Heure fin (débranchement)`), df6$`Heure début (branchement)` + mean(df6$`Heure fin (débranchement)`-df6$`Heure début (branchement)`, na.rm=T), df6$`Heure fin (débranchement)`)

df6$`Date séance`[is.na(df6$`Date séance`)] = 43745

temps = c(0)
for (i in seq(2,nrow(df6)+1,2)) {
  duree_seance = temps[i-1]+ (df6$`Heure fin (débranchement)`[i]-df6$`Heure début (branchement)`[i])*24*60
  duree_entre_seance = duree_seance + (df6$`Date séance`[i+1]-df6$`Date séance`[i])*24*60 + df6$`Heure début (branchement)`[i+1]*24*60
  temps = c(temps, duree_seance, duree_entre_seance)
}
layout(matrix(1,1),1)
plot(temps[1:20], df6$`MFI  CLASSE I`, type="l")
```

```{r}
df7 = subset(df, df$`Nom du Batch`=="Patient 7")

df7$`Heure fin (débranchement)` = ifelse(is.na(df7$`Heure fin (débranchement)`), df7$`Heure début (branchement)` + mean(df7$`Heure fin (débranchement)`-df7$`Heure début (branchement)`, na.rm=T), df7$`Heure fin (débranchement)`)

temps = c(0)
for (i in seq(2,nrow(df7)+1,2)) {
  duree_seance = temps[i-1]+ (df7$`Heure fin (débranchement)`[i]-df7$`Heure début (branchement)`[i])*24*60
  duree_entre_seance = duree_seance + (df7$`Date séance`[i+1]-df7$`Date séance`[i])*24*60 + df7$`Heure début (branchement)`[i+1]*24*60
  temps = c(temps, duree_seance, duree_entre_seance)
}
layout(matrix(1,1),1)
plot(temps[1:20], df7$`MFI  CLASSE I`, type="l")
```

```{r}
df8 = subset(df, df$`Nom du Batch`=="Patient 8")

df8$`Heure début (branchement)`[is.na(df8$`Heure début (branchement)`)] = mean(df8$`Heure début (branchement)`, na.rm=T)

df8$`Heure fin (débranchement)` = ifelse(is.na(df8$`Heure fin (débranchement)`), df8$`Heure début (branchement)` + mean(df8$`Heure fin (débranchement)`-df8$`Heure début (branchement)`, na.rm=T), df8$`Heure fin (débranchement)`)

temps = c(0)
for (i in seq(2,nrow(df8)+1,2)) {
  duree_seance = temps[i-1]+ (df8$`Heure fin (débranchement)`[i]-df8$`Heure début (branchement)`[i])*24*60
  duree_entre_seance = duree_seance + (df8$`Date séance`[i+1]-df8$`Date séance`[i])*24*60 + df8$`Heure début (branchement)`[i+1]*24*60
  temps = c(temps, duree_seance, duree_entre_seance)
}
layout(matrix(1,1),1)
plot(temps[1:20], df8$`MFI  CLASSE I`, type="l")
```

```{r}
df9 = subset(df, df$`Nom du Batch`=="Patient 9")

temps = c(0)
for (i in seq(2,nrow(df9)+1,2)) {
  duree_seance = temps[i-1]+ (df9$`Heure fin (débranchement)`[i]-df9$`Heure début (branchement)`[i])*24*60
  duree_entre_seance = duree_seance + (df9$`Date séance`[i+1]-df9$`Date séance`[i])*24*60 + df9$`Heure début (branchement)`[i+1]*24*60
  temps = c(temps, duree_seance, duree_entre_seance)
}
layout(matrix(1,1),1)
plot(temps[1:20], df9$`MFI  CLASSE I`, type="l")
```

```{r}
df10 = subset(df, df$`Nom du Batch`=="Patient 10")

df10$`Heure fin (débranchement)` = ifelse(is.na(df10$`Heure fin (débranchement)`), df10$`Heure début (branchement)` + mean(df$`Heure fin (débranchement)`-df$`Heure début (branchement)`, na.rm=T), df10$`Heure fin (débranchement)`)

temps = c(0)
for (i in seq(2,nrow(df10)+1,2)) {
  duree_seance = temps[i-1]+ (df10$`Heure fin (débranchement)`[i]-df10$`Heure début (branchement)`[i])*24*60
  duree_entre_seance = duree_seance + (df10$`Date séance`[i+1]-df10$`Date séance`[i])*24*60 + df10$`Heure début (branchement)`[i+1]*24*60
  temps = c(temps, duree_seance, duree_entre_seance)
}
layout(matrix(1,1),1)
plot(temps[1:20], df10$`MFI  CLASSE I`, type="l")
```

```{r}
df7_1 = subset(df, df$`Nom du Batch`=="Patient 7 1/5")

df7_1$`Heure fin (débranchement)` = ifelse(is.na(df7_1$`Heure fin (débranchement)`), df7_1$`Heure début (branchement)` + mean(df7_1$`Heure fin (débranchement)`-df7_1$`Heure début (branchement)`, na.rm=T), df7_1$`Heure fin (débranchement)`)

temps = c(0)
for (i in seq(2,nrow(df7_1)+1,2)) {
  duree_seance = temps[i-1]+ (df7_1$`Heure fin (débranchement)`[i]-df7_1$`Heure début (branchement)`[i])*24*60
  duree_entre_seance = duree_seance + (df7_1$`Date séance`[i+1]-df7_1$`Date séance`[i])*24*60 + df7_1$`Heure début (branchement)`[i+1]*24*60
  temps = c(temps, duree_seance, duree_entre_seance)
}
layout(matrix(1,1),1)
plot(temps[1:20], df7_1$`MFI CLASSE II`, type="l")
```

```{r}
df2_1 = subset(df, df$`Nom du Batch`=="Patient 2  1/10")

df2_1$`Heure fin (débranchement)` = ifelse(is.na(df2_1$`Heure fin (débranchement)`), df2_1$`Heure début (branchement)` + mean(df2_1$`Heure fin (débranchement)`-df2_1$`Heure début (branchement)`, na.rm=T), df2_1$`Heure fin (débranchement)`)

temps = c(0)
for (i in seq(2,nrow(df2_1)+1,2)) {
  duree_seance = temps[i-1]+ (df2_1$`Heure fin (débranchement)`[i]-df2_1$`Heure début (branchement)`[i])*24*60
  duree_entre_seance = duree_seance + (df2_1$`Date séance`[i+1]-df2_1$`Date séance`[i])*24*60 + df2_1$`Heure début (branchement)`[i+1]*24*60
  temps = c(temps, duree_seance, duree_entre_seance)
}
df2_1$temps = temps[1:20]
layout(matrix(1,1),1)
plot(temps[1:20], df2_1$`MFI  CLASSE I`, type="l")
```